#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIDao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CodeInspector")]
	public partial class CodeInspectorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHistoricoUsuario(HistoricoUsuario instance);
    partial void UpdateHistoricoUsuario(HistoricoUsuario instance);
    partial void DeleteHistoricoUsuario(HistoricoUsuario instance);
    partial void InsertQuestao(Questao instance);
    partial void UpdateQuestao(Questao instance);
    partial void DeleteQuestao(Questao instance);
    partial void InsertStatusUsuario(StatusUsuario instance);
    partial void UpdateStatusUsuario(StatusUsuario instance);
    partial void DeleteStatusUsuario(StatusUsuario instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public CodeInspectorDataContext() : 
				base(global::CIDao.Properties.Settings.Default.CodeInspectorConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CodeInspectorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeInspectorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeInspectorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CodeInspectorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HistoricoUsuario> HistoricoUsuarios
		{
			get
			{
				return this.GetTable<HistoricoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Questao> Questaos
		{
			get
			{
				return this.GetTable<Questao>();
			}
		}
		
		public System.Data.Linq.Table<StatusUsuario> StatusUsuarios
		{
			get
			{
				return this.GetTable<StatusUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HistoricoUsuario")]
	public partial class HistoricoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdHistorico;
		
		private int _IdUsuario;
		
		private int _IdQuestao;
		
		private System.Nullable<int> _QtdAcertos;
		
		private System.Nullable<int> _QtdErros;
		
		private EntityRef<Questao> _Questao;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHistoricoChanging(int value);
    partial void OnIdHistoricoChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnIdQuestaoChanging(int value);
    partial void OnIdQuestaoChanged();
    partial void OnQtdAcertosChanging(System.Nullable<int> value);
    partial void OnQtdAcertosChanged();
    partial void OnQtdErrosChanging(System.Nullable<int> value);
    partial void OnQtdErrosChanged();
    #endregion
		
		public HistoricoUsuario()
		{
			this._Questao = default(EntityRef<Questao>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHistorico", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdHistorico
		{
			get
			{
				return this._IdHistorico;
			}
			set
			{
				if ((this._IdHistorico != value))
				{
					this.OnIdHistoricoChanging(value);
					this.SendPropertyChanging();
					this._IdHistorico = value;
					this.SendPropertyChanged("IdHistorico");
					this.OnIdHistoricoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuestao", DbType="Int NOT NULL")]
		public int IdQuestao
		{
			get
			{
				return this._IdQuestao;
			}
			set
			{
				if ((this._IdQuestao != value))
				{
					if (this._Questao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdQuestaoChanging(value);
					this.SendPropertyChanging();
					this._IdQuestao = value;
					this.SendPropertyChanged("IdQuestao");
					this.OnIdQuestaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdAcertos", DbType="Int")]
		public System.Nullable<int> QtdAcertos
		{
			get
			{
				return this._QtdAcertos;
			}
			set
			{
				if ((this._QtdAcertos != value))
				{
					this.OnQtdAcertosChanging(value);
					this.SendPropertyChanging();
					this._QtdAcertos = value;
					this.SendPropertyChanged("QtdAcertos");
					this.OnQtdAcertosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QtdErros", DbType="Int")]
		public System.Nullable<int> QtdErros
		{
			get
			{
				return this._QtdErros;
			}
			set
			{
				if ((this._QtdErros != value))
				{
					this.OnQtdErrosChanging(value);
					this.SendPropertyChanging();
					this._QtdErros = value;
					this.SendPropertyChanged("QtdErros");
					this.OnQtdErrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Questao_HistoricoUsuario", Storage="_Questao", ThisKey="IdQuestao", OtherKey="IdQuestao", IsForeignKey=true)]
		public Questao Questao
		{
			get
			{
				return this._Questao.Entity;
			}
			set
			{
				Questao previousValue = this._Questao.Entity;
				if (((previousValue != value) 
							|| (this._Questao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Questao.Entity = null;
						previousValue.HistoricoUsuarios.Remove(this);
					}
					this._Questao.Entity = value;
					if ((value != null))
					{
						value.HistoricoUsuarios.Add(this);
						this._IdQuestao = value.IdQuestao;
					}
					else
					{
						this._IdQuestao = default(int);
					}
					this.SendPropertyChanged("Questao");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_HistoricoUsuario", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.HistoricoUsuarios.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.HistoricoUsuarios.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Questao")]
	public partial class Questao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdQuestao;
		
		private int _NivelDificuldade;
		
		private string _XmlQuestao;
		
		private System.Nullable<int> _Tempo;
		
		private EntitySet<HistoricoUsuario> _HistoricoUsuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdQuestaoChanging(int value);
    partial void OnIdQuestaoChanged();
    partial void OnNivelDificuldadeChanging(int value);
    partial void OnNivelDificuldadeChanged();
    partial void OnXmlQuestaoChanging(string value);
    partial void OnXmlQuestaoChanged();
    partial void OnTempoChanging(System.Nullable<int> value);
    partial void OnTempoChanged();
    #endregion
		
		public Questao()
		{
			this._HistoricoUsuarios = new EntitySet<HistoricoUsuario>(new Action<HistoricoUsuario>(this.attach_HistoricoUsuarios), new Action<HistoricoUsuario>(this.detach_HistoricoUsuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuestao", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdQuestao
		{
			get
			{
				return this._IdQuestao;
			}
			set
			{
				if ((this._IdQuestao != value))
				{
					this.OnIdQuestaoChanging(value);
					this.SendPropertyChanging();
					this._IdQuestao = value;
					this.SendPropertyChanged("IdQuestao");
					this.OnIdQuestaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivelDificuldade", DbType="Int NOT NULL")]
		public int NivelDificuldade
		{
			get
			{
				return this._NivelDificuldade;
			}
			set
			{
				if ((this._NivelDificuldade != value))
				{
					this.OnNivelDificuldadeChanging(value);
					this.SendPropertyChanging();
					this._NivelDificuldade = value;
					this.SendPropertyChanged("NivelDificuldade");
					this.OnNivelDificuldadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XmlQuestao", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string XmlQuestao
		{
			get
			{
				return this._XmlQuestao;
			}
			set
			{
				if ((this._XmlQuestao != value))
				{
					this.OnXmlQuestaoChanging(value);
					this.SendPropertyChanging();
					this._XmlQuestao = value;
					this.SendPropertyChanged("XmlQuestao");
					this.OnXmlQuestaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tempo", DbType="Int")]
		public System.Nullable<int> Tempo
		{
			get
			{
				return this._Tempo;
			}
			set
			{
				if ((this._Tempo != value))
				{
					this.OnTempoChanging(value);
					this.SendPropertyChanging();
					this._Tempo = value;
					this.SendPropertyChanged("Tempo");
					this.OnTempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Questao_HistoricoUsuario", Storage="_HistoricoUsuarios", ThisKey="IdQuestao", OtherKey="IdQuestao")]
		public EntitySet<HistoricoUsuario> HistoricoUsuarios
		{
			get
			{
				return this._HistoricoUsuarios;
			}
			set
			{
				this._HistoricoUsuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HistoricoUsuarios(HistoricoUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Questao = this;
		}
		
		private void detach_HistoricoUsuarios(HistoricoUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Questao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StatusUsuario")]
	public partial class StatusUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdStatus;
		
		private int _IdUsuario;
		
		private int _Pontuacao;
		
		private System.DateTime _DataInsercao;
		
		private int _NivilDificuldade;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdStatusChanging(int value);
    partial void OnIdStatusChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnPontuacaoChanging(int value);
    partial void OnPontuacaoChanged();
    partial void OnDataInsercaoChanging(System.DateTime value);
    partial void OnDataInsercaoChanged();
    partial void OnNivilDificuldadeChanging(int value);
    partial void OnNivilDificuldadeChanged();
    #endregion
		
		public StatusUsuario()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdStatus", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdStatus
		{
			get
			{
				return this._IdStatus;
			}
			set
			{
				if ((this._IdStatus != value))
				{
					this.OnIdStatusChanging(value);
					this.SendPropertyChanging();
					this._IdStatus = value;
					this.SendPropertyChanged("IdStatus");
					this.OnIdStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pontuacao", DbType="Int NOT NULL")]
		public int Pontuacao
		{
			get
			{
				return this._Pontuacao;
			}
			set
			{
				if ((this._Pontuacao != value))
				{
					this.OnPontuacaoChanging(value);
					this.SendPropertyChanging();
					this._Pontuacao = value;
					this.SendPropertyChanged("Pontuacao");
					this.OnPontuacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInsercao", DbType="DateTime NOT NULL")]
		public System.DateTime DataInsercao
		{
			get
			{
				return this._DataInsercao;
			}
			set
			{
				if ((this._DataInsercao != value))
				{
					this.OnDataInsercaoChanging(value);
					this.SendPropertyChanging();
					this._DataInsercao = value;
					this.SendPropertyChanged("DataInsercao");
					this.OnDataInsercaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NivilDificuldade", DbType="Int NOT NULL")]
		public int NivilDificuldade
		{
			get
			{
				return this._NivilDificuldade;
			}
			set
			{
				if ((this._NivilDificuldade != value))
				{
					this.OnNivilDificuldadeChanging(value);
					this.SendPropertyChanging();
					this._NivilDificuldade = value;
					this.SendPropertyChanged("NivilDificuldade");
					this.OnNivilDificuldadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_StatusUsuario", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.StatusUsuarios.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.StatusUsuarios.Add(this);
						this._IdUsuario = value.IdUsuario;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUsuario;
		
		private string _Nome;
		
		private string _Email;
		
		private string _Senha;
		
		private string _Login;
		
		private EntitySet<HistoricoUsuario> _HistoricoUsuarios;
		
		private EntitySet<StatusUsuario> _StatusUsuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    #endregion
		
		public Usuario()
		{
			this._HistoricoUsuarios = new EntitySet<HistoricoUsuario>(new Action<HistoricoUsuario>(this.attach_HistoricoUsuarios), new Action<HistoricoUsuario>(this.detach_HistoricoUsuarios));
			this._StatusUsuarios = new EntitySet<StatusUsuario>(new Action<StatusUsuario>(this.attach_StatusUsuarios), new Action<StatusUsuario>(this.detach_StatusUsuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(30)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(15)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_HistoricoUsuario", Storage="_HistoricoUsuarios", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<HistoricoUsuario> HistoricoUsuarios
		{
			get
			{
				return this._HistoricoUsuarios;
			}
			set
			{
				this._HistoricoUsuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_StatusUsuario", Storage="_StatusUsuarios", ThisKey="IdUsuario", OtherKey="IdUsuario")]
		public EntitySet<StatusUsuario> StatusUsuarios
		{
			get
			{
				return this._StatusUsuarios;
			}
			set
			{
				this._StatusUsuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HistoricoUsuarios(HistoricoUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_HistoricoUsuarios(HistoricoUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_StatusUsuarios(StatusUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_StatusUsuarios(StatusUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
}
#pragma warning restore 1591
