<?xml version="1.0" encoding="utf-8"?><Database Name="CodeInspector" Class="CodeInspectorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ENUMA-PC;Initial Catalog=CodeInspector;Integrated Security=True" SettingsObjectName="Database.Properties.Settings" SettingsPropertyName="CodeInspectorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HistoricoUsuario" Member="HistoricoUsuarios">
    <Type Name="HistoricoUsuario">
      <Column Name="IdHistorico" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdQuestao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QtdAcertos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QtdErros" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Questao_HistoricoUsuario" Member="Questao" ThisKey="IdQuestao" OtherKey="IdQuestao" Type="Questao" IsForeignKey="true" />
      <Association Name="Usuario_HistoricoUsuario" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Questao" Member="Questaos">
    <Type Name="Questao">
      <Column Name="IdQuestao" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NivelDificuldade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="XmlQuestao" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Tempo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Questao_HistoricoUsuario" Member="HistoricoUsuarios" ThisKey="IdQuestao" OtherKey="IdQuestao" Type="HistoricoUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.StatusUsuario" Member="StatusUsuarios">
    <Type Name="StatusUsuario">
      <Column Name="IdStatus" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pontuacao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataInsercao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NivilDificuldade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_StatusUsuario" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Senha" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Association Name="Usuario_HistoricoUsuario" Member="HistoricoUsuarios" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="HistoricoUsuario" />
      <Association Name="Usuario_StatusUsuario" Member="StatusUsuarios" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="StatusUsuario" />
    </Type>
  </Table>
</Database>