<?xml version="1.0" encoding="utf-8"?><Database Name="CodeInspector" Class="InspectorXDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ENUMA-PC;Initial Catalog=CodeInspector;Integrated Security=True" SettingsObjectName="CIDao.Properties.Settings" SettingsPropertyName="CodeInspectorConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="U_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="U_NOME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="U_EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="U_SENHA" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="U_LOGIN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Usuario_Partida" Member="Partidas" ThisKey="U_ID" OtherKey="U_ID" Type="Partida" />
    </Type>
  </Table>
  <Table Name="dbo.Historico_Questao" Member="Historico_Questaos">
    <Type Name="Historico_Questao">
      <Column Name="H_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="H_QTD_ACERTO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="H_QTD_ERRO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Partida_Historico_Questao" Member="Partida" ThisKey="P_ID" OtherKey="P_ID" Type="Partida" IsForeignKey="true" />
      <Association Name="Questao_Historico_Questao" Member="Questao" ThisKey="Q_ID" OtherKey="Q_ID" Type="Questao" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItemTaxonomia" Member="ItemTaxonomias">
    <Type Name="ItemTaxonomia">
      <Column Name="IT_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IT_Nome" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IT_Descricao" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ItemTaxonomia_TrechoDefeito" Member="TrechoDefeitos" ThisKey="IT_ID" OtherKey="IT_ID" Type="TrechoDefeito" />
      <Association Name="Taxonomia_ItemTaxonomia" Member="Taxonomia" ThisKey="T_ID" OtherKey="T_ID" Type="Taxonomia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Partida" Member="Partidas">
    <Type Name="Partida">
      <Column Name="P_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="U_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P_DATA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="P_NIVEL_DIFICULDADE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="P_PONTUACAO_TOTAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Partida_Historico_Questao" Member="Historico_Questaos" ThisKey="P_ID" OtherKey="P_ID" Type="Historico_Questao" />
      <Association Name="Usuario_Partida" Member="Usuario" ThisKey="U_ID" OtherKey="U_ID" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Questao" Member="Questaos">
    <Type Name="Questao">
      <Column Name="Q_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Q_NIVEL_DIFICULDADE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q_XML" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Q_TEMPO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MotivoErroId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Q_Nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Questao_Historico_Questao" Member="Historico_Questaos" ThisKey="Q_ID" OtherKey="Q_ID" Type="Historico_Questao" />
      <Association Name="Questao_Questao_TrechoDefeito" Member="Questao_TrechoDefeitos" ThisKey="Q_ID" OtherKey="Q_id" Type="Questao_TrechoDefeito" />
    </Type>
  </Table>
  <Table Name="dbo.Questao_TrechoDefeito" Member="Questao_TrechoDefeitos">
    <Type Name="Questao_TrechoDefeito">
      <Column Name="Q_TD_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Q_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TD_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="respondido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Questao_Questao_TrechoDefeito" Member="Questao" ThisKey="Q_id" OtherKey="Q_ID" Type="Questao" IsForeignKey="true" />
      <Association Name="TrechoDefeito_Questao_TrechoDefeito" Member="TrechoDefeito" ThisKey="TD_id" OtherKey="D_ID" Type="TrechoDefeito" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Taxonomia" Member="Taxonomias">
    <Type Name="Taxonomia">
      <Column Name="T_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="T_Nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Taxonomia_ItemTaxonomia" Member="ItemTaxonomias" ThisKey="T_ID" OtherKey="T_ID" Type="ItemTaxonomia" />
      <Association Name="Taxonomia_TipoArtefato_Taxonomia" Member="TipoArtefato_Taxonomias" ThisKey="T_ID" OtherKey="T_ID" Type="TipoArtefato_Taxonomia" />
    </Type>
  </Table>
  <Table Name="dbo.TipoArtefato" Member="TipoArtefatos">
    <Type Name="TipoArtefato">
      <Column Name="TA_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TA_DESCRICAO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TA_NOME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="TipoArtefato_TipoArtefato_Taxonomia" Member="TipoArtefato_Taxonomias" ThisKey="TA_ID" OtherKey="TA_ID" Type="TipoArtefato_Taxonomia" />
    </Type>
  </Table>
  <Table Name="dbo.TipoArtefato_Taxonomia" Member="TipoArtefato_Taxonomias">
    <Type Name="TipoArtefato_Taxonomia">
      <Column Name="TA_T_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="T_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TA_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Taxonomia_TipoArtefato_Taxonomia" Member="Taxonomia" ThisKey="T_ID" OtherKey="T_ID" Type="Taxonomia" IsForeignKey="true" />
      <Association Name="TipoArtefato_TipoArtefato_Taxonomia" Member="TipoArtefato" ThisKey="TA_ID" OtherKey="TA_ID" Type="TipoArtefato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TrechoDefeito" Member="TrechoDefeitos">
    <Type Name="TrechoDefeito">
      <Column Name="D_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IT_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="D_Explicacao" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="D_Conteudo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="TrechoDefeito_Questao_TrechoDefeito" Member="Questao_TrechoDefeitos" ThisKey="D_ID" OtherKey="TD_id" Type="Questao_TrechoDefeito" />
      <Association Name="ItemTaxonomia_TrechoDefeito" Member="ItemTaxonomia" ThisKey="IT_ID" OtherKey="IT_ID" Type="ItemTaxonomia" IsForeignKey="true" />
    </Type>
  </Table>
</Database>